CASecurity/CASecurity.Web/Controllers/AdminController.cs
using CASecurity.Web.Models;
using Castle.Core.Logging;
using System.Collections.Generic;
using CASecurity.Web.ViewModelBuilders;
using System.Web.Mvc;
using System.Linq;
using System;
using System.IO;
using CASecurity.Service;
using CASecurity.Domain.Dtos;
using System.Web;
using CASecurity.Web.Utility;
using PagedList;

namespace CASecurity.Web.Controllers
{
    public class AdminController : Controller
    {
        private ILogger _logger = NullLogger.Instance;

        private readonly IBankService _bankService;
        private readonly IMerchantService _merchantService;
        private readonly IAppService _appService;
        private readonly ViewModelBuilder _viewModelBuilder;

        public AdminController()
        {
            _bankService = new BankService();
            _merchantService = new MerchantService();
            _appService = new AppService();
            _viewModelBuilder = new ViewModelBuilder(_bankService, _merchantService, _appService);
        }

        #region Bank
        public ActionResult Bank(int? page)
        {
            var model = new List<BankModel>();

            try
            {
                model = _viewModelBuilder.GetBanks();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View(model.ToPagedList(page ?? 1, Context.PageSize));
        }

        [HttpGet]
        public ActionResult CreateBank(string id)
        {
            var model = new BankModel();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    model = _viewModelBuilder.GetBank(id);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return PartialView("_CreateBank", model);
        }

        [HttpPost]
        public ActionResult CreateBank(BankModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _viewModelBuilder.SaveBank(model);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction("Bank");
        }

        public ActionResult DeleteBank(Guid id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _bankService.Delete(id);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction("Bank");
        }
        #endregion

        #region Merchant
        public ActionResult Merchant()
        {
            var model = new List<MerchantModel>();
            try
            {
                model = _viewModelBuilder.GetMerchants();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult CreateMerchant(string id)
        {
            var model = new MerchantModel();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    model = _viewModelBuilder.GetMerchant(id);
                }

                var list = (from l in _bankService.Get()
                            where l.IsActive && l.Name != null
                            select new SelectListItem
                            {
                                Text = l.Name,
                                Value = l.Id.ToString()
                            });

                ViewBag.Banks = list;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return PartialView("_CreateMerchant", model);
        }

        [HttpPost]
        public ActionResult CreateMerchant(MerchantModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _viewModelBuilder.SaveMerchant(model);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction(model.RedirectTo);
        }

        public ActionResult DeleteMerchant(Guid id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _merchantService.Delete(id);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction("Merchant");
        }
        #endregion

        #region Apps
        public ActionResult AppList(string bankId, string merchantId)
        {
            var model = new ApplistModel();

            try
            {
                model = _viewModelBuilder.GetAppList(bankId, merchantId);
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View(model);
        }

        public ActionResult App(string id)
        {
            var model = new BankMerchantModel
            {
                Apps = new List<AppModel>(),
                Banks = new List<SelectListItem>(),
                Merchants = new List<SelectListItem>(),
                Code = string.Empty
            };
            try
            {
                var banks = (from l in _bankService.Get()
                             where l.IsActive && l.Name != null
                             select new SelectListItem
                             {
                                 Text = l.Name,
                                 Value = l.Id.ToString()
                             }).ToList();

                var merchants = (from l in _merchantService.Get()
                                 where l.IsActive && l.Name != null
                                 select new SelectListItem
                                 {
                                     Text = l.Name,
                                     Value = l.Id.ToString()
                                 }).ToList();

                ViewBag.Banks = banks;
                ViewBag.Merchants = merchants;

                model = new BankMerchantModel
                {
                    Apps = new List<AppModel>(),
                    Banks = banks,
                    Merchants = merchants,
                    Code = string.Empty
                };

                if (!string.IsNullOrEmpty(id))
                {
                    var bankMerchant = _appService.GetBankMerchant(new Guid(id));
                    if (bankMerchant != null)
                    {
                        model.BankId = bankMerchant.BankId.ToString();
                        model.MerchantId = bankMerchant.MerchantId.ToString();
                    }
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        //[HttpPost]
        //public ActionResult App(AppModel model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            model.BMCode = model.Code;
        //            var isExist = _appService.FindBankMerchant(new Guid(model.BankId), new Guid(model.MerchantId));
        //            if (isExist == null)
        //            {
        //                var merchant = new BankMerchant
        //                {
        //                    Code = model.BMCode,
        //                    BankId = new Guid(model.BankId),
        //                    MerchantId = new Guid(model.MerchantId),
        //                };
        //                _appService.InsertBankMerchant(merchant);
        //                model.BankMerchantId = merchant.Id.ToString();
        //            }

        //            if (string.IsNullOrEmpty(model.BankMerchantId))
        //                model.BankMerchantId = isExist.Id.ToString();

        //            //get bank
        //            var bankCode = _bankService.Get(new Guid(model.BankId)).Code;
        //            //get merchant
        //            var merchantCode = _merchantService.Get(new Guid(model.MerchantId)).Code;

        //            var app = new App
        //            {
        //                Code = model.Code,
        //                BankMerchantId = new Guid(model.BankMerchantId),
        //                Address = string.Empty,
        //                Name = model.Name,
        //                Package = model.Package,
        //                PlatForm = model.PlatForm,
        //                Production = string.Empty,
        //                SandBox = string.Empty,
        //                IsActive = true,
        //                CreatedDateTime = DateTime.Now,
        //                JustPayCode = bankCode + "_" + merchantCode + "_" + model.Code,
        //            };

        //            _appService.Save(app);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }

        //    return RedirectToAction("App");
        //}

        public ActionResult CreateApp(string id)
        {
            var model = new AppModel();
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    model = _viewModelBuilder.GetApp(id);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return PartialView("_CreateApp", model);
        }

        [HttpPost]
        public ActionResult CreateApp(AppModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _viewModelBuilder.SaveApp(model);
                }
            }
            catch (Exception ex)
            {

CASecurity/CASecurity.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CASecurity.Web.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
    }
}

CASecurity/CASecurity.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/common")
    @*@Scripts.Render("~/bundles/jqueryupload")*@
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LC-Console", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bank", "Bank", "Admin", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Merchant", "Merchant", "Admin", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("App", "App", "Admin", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Reports", "Index", "Report", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year  By mBrain</p>
        </footer>
    </div>

    <!--Confirm message-->
    <div id="confirm" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-body" id="confirmMessage">
                Are you sure?
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-primary" id="okBtn">Remove</button>
                <button type="button" data-dismiss="modal" class="btn" id="cancelBtn">Cancel</button>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>